### ISSUE TITLE
Omitting the length/count fields

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-bakery/nom-derive#15]
With nom-derive, it is currently possible to parse an integer field and then use it as a count to parse the next n items:
```
    num_items: u32,
    #[nom(Count="num_items")]
    items: Vec<Item>,
```

While this in itself is a nice feature, it would be nice if the `num_items` field could be omitted as that information is already encoded in `items.len()` and as that avoids the situation where you try to serialize the struct that you have to update the `num_items` field or sprinkle `#[serde(skip_serializing)]` all over the place.

My current solution is to implement the following to parse the count and then use it to parse the items of type `Vec<T>`:
```
pub fn sized_vec<I, O, E, F>(f: F) -> impl FnMut(I) -> nom::IResult<I, Vec<O>, E>
where
    I: Clone + PartialEq + nom::Slice<std::ops::RangeFrom<usize>> + nom::InputIter<Item = u8> + nom::InputLength,
    F: Clone + FnMut(I) -> nom::IResult<I, O, E>,
    E: nom::error::ParseError<I>,
{
    move |i: I| {
        let (i, count) = nom::number::complete::le_u32(i)?;
        nom::multi::count(f.clone(), count as usize)(i)
    }
}
```

Then you can rewrite the aforementioned example as:
```
    #[nom(Parse="sized_vec(Item::parse)"]
    items: Vec<Item>,
```

However, having to do this for every `Vec<T>` is a bit cumbersome.

**Comment by chifflier** [comment]
This looks similar to the [`length_count`](https://docs.rs/nom/6.1.2/nom/multi/fn.length_count.html) combinator of `nom`.
A solution could be to add a new custom attribute:
```rust
struct S {
    #[nom(LengthCount="be_u32")]
    items: Vec<Item>,
```
Assuming that the parser for `Item` can be inferred automatically.

Would that be fine for you?

**Comment by StephanvanSchaik** [comment]
I actually completely missed that combinator when looking at the Nom documentation. Having that combinator would be absolutely perfect.
