### ISSUE TITLE
Document how to implement parsers for existing types

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-bakery/nom-derive#16]
I am not sure if this is the cleanest way to currently approach having a general parser for existing types like `bool`, `f32`, `f64`, `String`, etc. where you can't normally implement `S::parse(&[u8]) -> IResult<&[u8], Self>` yourself, but it would probably be good to include an example like the following:

```
trait Parse {
    fn parse(i: &[u8]) -> nom::IResult<&[u8], Self>
    where
        Self: Sized;
}

impl Parse for f32 {
    fn parse(i: &[u8]) -> nom::IResult<&[u8], Self> {
        le_f32(i)
    }
}
```

The above example allows you to implement `S::parse()` for existing types like `bool`, `f32`, `f64`, `String`, etc. such that you can just use them in your `struct`, without having to specify something like `#[nom(Parse="le_f32")]` for every `f32` field. It would probably be good to mention this in the documentation.

**Comment by chifflier** [comment]
`f32` and `f64` can be added to the known primitive types.

However, some of the types you describe do not have a standard binary representation, like `String` or `bool` (which parsing function should be called?).
A possible solution is to declare a newtype and implement `Parse` on it:
```rust
pub struct MyString(pub String);

impl Parse for MyString {
// ...
}
```

That way, declaring the field as `MyString` will be enough to derive the parser.

**Comment by StephanvanSchaik** [comment]
Yes, I think the issue is a bit two-fold. For `f32` and `f64` it would make sense to add them to the known primitive types given that Nom already provides `be_f32`, `le_f32`, `be_f64` and `le_f64`. For `bool` and `String`, you definitely would want to keep the flexibility, as it will differ a lot from parser to parser how to interpret those. e.g. for what I am trying to parse, a `bool` is an 8-bit integer where 1 is true and 0 is false, and a `String` starts with a variable length integer denoting the size (whereas someone else might want to parse null-terminated strings).

Your newtype approach makes a bit more sense, as it avoids fixing how `String` and `bool` are parsed and instead provides new types with the particular parsing behaviour (e.g. that way you could have type for length-prefixed strings as well as a type for null-terminated strings). It would be good to at the very minimum have an example like that in the documentation.

**Comment by StephanvanSchaik** [comment]
Also, I totally forgot, but I have been trying to play around with newtype idea for `Vec<T>` such that I could have a `SizedVec<T>` where it first parses the size and then the items, but what seems to be missing for that is a trait `Parse` where everything generated by nom-derive implements that trait, such that you could do: `impl<T: Parse> Parse for SizedVec<T> {` (related to issue #15).

**Comment by chifflier** [comment]
I had previously avoided using a Trait because a `proc-macro` crate cannot provide both public objects (like Traits) and proc macros. That said, I agree this would be nice to have, and would make APIs more consistent.
I'll have a look. It seems the common method is to break the crate in multiple crates (like `thiserror` and `thiserror-impl`), and have everything re-exported in the "public" crate.

**Comment by chifflier** [comment]
The code has been refactored in the 0.8 branch, and this is now supported in branch [dev/refactor-v0.2](https://github.com/rust-bakery/nom-derive/tree/dev/refactor-v0.2): the crate has been split in 2 (`nom-derive` and `nom-derive-impl`), and now provides a `Parse` trait with implementation for default types, and documentation on how to extend.
Scheduled for 0.8
