### ISSUE TITLE
Complete/Streaming default for parsers (was: Generation of bytes module's parsers)

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom-derive#17]
Personally I think that's the most data should be parsed with `complete` as it's provided full of length. It's ok when someone is trying to parse things such as network packages so they need `nom::bytes::streaming` module. But it's really rare case in my opinion. 
So I propose to change all parsers such as `streaming::le_u32` to `complete::le_u32` and so on. Or there should be feature to switch mode.

**Comment by r4v3n6101** [comment]
I like such idea because it seems fine as `complete` data may be whole structure but not only part of it.

**Comment by chifflier** [comment]
`Complete` can now be applied at top-level, and will apply to all fields.
