### ISSUE TITLE
Allow `()` for `Tag`

### ISSUE THREAD

**Issue by reactormonk** [rust-bakery/nom-derive#18]
Currently, `Tag` requires a `&[u8]`, which causes all kinds of issues regarding copying the resulting data around. It would be nice if the resulting type could also be `()` to throw the data away.

**Comment by chifflier** [comment]
Hi,
The code has been refactored in the 0.8 branch, and this is now supported in branch [dev/refactor-v0.2](https://github.com/rust-bakery/nom-derive/tree/dev/refactor-v0.2): the order of attributes describes the actions, so it is now possible to specify
```rust
#[derive(Nom)]
struct IgnoreTag {
    #[nom(Ignore, Tag(b"TAG"))]
    tag: (),
    a: u16,
    b: u16,
}
```

This is planned for 0.8
