### ISSUE TITLE
Error parsing Strings

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom-derive#32]
In short, applying `derive(Nom) + nom(GenericErrors)` to structure with `String` parameter will give you error of type incompliance: generated `NomErr` must be `NomErr: FromExternalError<&[u8], Utf8Error>`

**Comment by chifflier** [comment]
Bug confirmed.
Fixing it requires some changes in the code generation, to store the list of trait bounds on the impl block (#35 ) before the actual fix.
