### ISSUE TITLE
Support for primitive arrays

### ISSUE THREAD

**Issue by xd009642** [rust-bakery/nom-derive#4]
Is there a way using the attributes to help it parse into types such as: `[u8; 4]`? Currently Nom isn't derived for them so I appreciate there might be some finagling to do. Although it seems like something that could have a sensible default derivation

**Comment by chifflier** [comment]
It seems possible, but will depend on the primitive type element.
For `[u8; 4]`, it can be done using the `TryInto` trait, so `nom-derive` could generate code like:
```rust
    let (i, a) = take(4usize)(i)?;
    let a = {
        use std::convert::TryInto;
        a.try_into()
            .or(Err(nom::Err::Error((i, nom::error::ErrorKind::MapRes))))
    }?;
```

However, if the primitive type is not `u8`, it would require either unsafe code (`mem::transmute` for ex.) or copying elements (which may not be a so bad strategy, but not zero-copy).
