### ISSUE TITLE
Count with Parse

### ISSUE THREAD

**Issue by r4v3n6101** [rust-bakery/nom-derive#9]
Make possible to combine Parse and Count. Currently we can't do such combination: 
```rust
#[derive(Nom)]
struct A {
    num: u8,
    #[nom(Parse = "{|i| Enum::parse(i, external_field) }", Count = "num"]
    v: Vec<Enum>,
}
...
nom::multi::count({|i| Enum::parse(i, external_field)}, { num } as usize)
```

**Comment by chifflier** [comment]
Currently, `Parse` overrides almost anything you provide after.
So, the idea would be that if both `Count` and `Parse` are provided, `Parse` is interpreted as parsing function for each item?

It seems possible, though maybe requiring to refactor some code (which is a good thing)

**Comment by r4v3n6101** [comment]
Maybe there's should be a new one. Kinda "ParseElement".
